### ISSUE TITLE
Modify Footer

### ISSUE THREAD

**Issue by chrswng** [GovLab/smarter-crowdsourcing-splash#3]
Move about to right side, use smarter crowdsourcing logo in center

**Comment by ghost** [comment]
i think this was already fixed, or im not understanding
<img width="1280" alt="screen shot 2017-08-30 at 1 02 02 am" src="https://user-images.githubusercontent.com/1042629/29849459-db6a8b12-8d1e-11e7-9bbd-8a7fa0b4b1b6.png">
